name:                ps-game-price-history
version:             0.1.0.0

dependencies:
- aeson
- aeson-pretty
- base
- bytestring
- containers
- directory
- filepath
- http-client
- http-client-tls
- hslogger
- pipes
- unordered-containers
- text
- time

executables:
  ps-game-price-history:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N